version: '3.8'

services:
  social-app-java:
    build: .
    #entrypoint: "java,-cp,app:app/lib/*,ru.kuzmin.socialnethl.SocialNetHlApplication"
    restart: on-failure
    environment:
      - PGHOST=db
      - PGPORT=5432
    ports:
      - "8080:8080"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
